name: Build and Push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Junit tests
      run:  mvn test 
    - name: Build and push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: sayanhub1996/springboot-app
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    

  demo:
    needs: build
    #if pull request merged then only this job will run
    if: github.ref == 'refs/heads/main'  && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Dummty step
      run: echo "Hi!! " ${{ vars.DEFAULT_MESSAGE }} 


  docker-push:
    needs: build
    #if pull request merged then only this job will run
    #if: github.ref == 'refs/heads/main'  && github.event.pull_request.merged
    runs-on: ubuntu-latest
    uses: mr-smithers-excellent/docker-build-push@v4
    with:
      image: sayanhub1996/springboot-app
      tag: latest
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

